config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 5, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
belongs_to :article
belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user  # changes current_user in a boolean
  end

  def require_user
    if !logged_in?
      flash[:alert] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was updated'
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    flash[:alert] = 'Article deleted'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own article'
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category was updated'
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was created successfully'
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else
      flash.now[:alert] = 'Email or password incorrect'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account information was successfully updated'
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.username.capitalize} welcome to the Alpha blog."
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Account and all associated articles successdully deleted'
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own account'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 200 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded mx-auto d-block')
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center ">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user), style: "text-decoration: none;" %>
            <% end %>

            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %></div>
            <% end %>
          </div>

          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-info" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <div class="btn-group justify-content-between">
              <%= link_to "View", article_path(article), class: "btn btn-outline-info border-0" %>
              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-success border-0" %>
                <%= button_to "Delete", article_path(article), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "btn btn-outline-danger border-0" %>
              <% end %>
            </div>
          </div>

          <div class="card-footer text-body-secondary">
            <small>
              Created <%= time_ago_in_words(article.created_at) %> ago,
              edited <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_with(model: @article, local: true) do |f| %>
  <div class="form-group row">
    <div class="col-8 mx-auto mb-4">
      <%= f.text_field :title, class: "form-control", placeholder: 'Title' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-8 mx-auto mb-4">
      <%= f.text_area :description, rows: 10, class: "form-control", placeholder: 'Description of article' %>
    </div>
  </div>

  <div class="form-group row mb-4">
    <div class="col-8 mx-auto">
      <%= f.collection_select(:category_ids, Category.all, :id, :name,
      { prompt: "Make a selection of categories from the list below (can be empty)" },
      { multiple: true, size: 4, class: "custom-select col-12 shadow rounded border border-none" }) %>
    </div>
  </div>

  <div class="form-group text-center mb-4">
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
      <%= f.submit class: "btn btn-info"%>
      <%= link_to "Back to list", articles_path, class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 mb-4">Listing all articles</h1>

<div class="apple_pagination mx-auto">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="apple_pagination mx-auto mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>

<div class="container">
  <div class="row justify-content-md-center ">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header fst-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user, size: 120), user_path(@article.user) %>
          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>
        </div>

        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <div class="btn-group justify-content-between">
            <%= link_to "Back", articles_path, class: "btn btn-outline-secondary border-0" %>
            <% if logged_in? && (@article.user == current_user  || current_user.admin?)%>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-success border-0" %>
              <%= button_to "Delete", article_path(@article), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "btn btn-outline-danger border-0" %>
            <% end %>
          </div>
        </div>

        <div class="card-footer text-body-secondary">
          <small>
            Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category),
class:"badge rounded-pill text-bg-info",
style: "text-decoration: none;" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_with(model: @category, local: true) do |f| %>
  <div class="form-group row">
    <div class="col-3 mx-auto mb-4">
      <%= f.text_field :name, class: "form-control", placeholder: 'Name' %>
    </div>
  </div>

  <div class="form-group text-center">
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
      <%= f.submit class: "btn btn-info" %>
      <%= link_to "Back to list", categories_path, class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit category name</h1>

<%=  render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-4">Categories</h1>

<div class="apple_pagination mx-auto">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center ">
      <div class="col-5 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-info" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>

          <div class="card-footer text-body-secondary">
            <small>
              Created <%= time_ago_in_words(category.created_at) %> ago,
              edited <%= time_ago_in_words(category.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="apple_pagination mx-auto">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 mb-4">Create a new category</h1>

<%=  render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category <%= @category.name %></h1>

<div class="text-center mt-4">
  <%= link_to "Back to list", categories_path, class: "btn btn-secondary" %>
  <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-success" %>
  <% end %>
</div>

<h2 class="text-center mt-4">Articles</h2>

<div class="apple_pagination mx-auto">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination mx-auto mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="footer mt-auto py-3 bg-primary text-white text-center" >
  <div class="container">
    <small class="fw-bold fs-5" style="color: #212529;"> © MariusTulbure, 2023 </small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade-show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" ></button>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger alert-dismissible fade-show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" ></button>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Alpha blog", root_path, class: "navbar-brand fs-2 text-info outlined-text", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 fw-bold fs-5">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link"  %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
              <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Articles list", articles_path, class: "dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Categories list", categories_path, class: "dropdown-item" %>
          </ul>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile <%= current_user.username %>
            </a>
            <ul class="dropdown-menu">
              <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= button_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete } %>
            </ul>
          </li>

          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link"  %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column" id="page-content">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to "Articles list", articles_path %> |
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="p-5 mb-4 rounded-3 bg-transparent">
    <div class="container-fluid py-5 text-center text-dark">
      <h1 class="display-3 fw-bold">Alpha blog</h1>
      <p class="col-md-8 fs-4 mx-auto fw-bold" style="max-width: 800px;">
        Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.
      </p>

      <p>
        <%= link_to "Sign up", signup_path, class:"btn btn-info" %>
        <%= link_to "About page", about_path, class:"btn btn-info"%>
      </p>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<div class="container col-8">
  <% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade-show" role="alert">
      <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h4>
      <ul>
        <% obj.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" ></button>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group row mb-4">
    <div class="col-3 mx-auto">
      <%= f.text_field :username, class: "form-control", placeholder: 'Username' %>
    </div>
  </div>

  <div class="form-group row mb-4">
    <div class="col-3 mx-auto">
      <%= f.email_field :email, class: "form-control", placeholder: 'Email' %>
    </div>
  </div>

  <div class="form-group row mb-4">
    <div class="col-3 mx-auto">
      <%= f.password_field :password, class: "form-control", placeholder: 'Password' %>
    </div>
  </div>

  <div class="form-group text-center mb-4">
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
      <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-info") %>
      <%= link_to "Back to list", users_path, class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha bloggers</h1>

<div class="apple_pagination mx-auto">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center ">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <%= link_to user.username, user %>
          </div>

          <div class="card-body">
            <h5 class="card-title"><%= link_to gravatar_for(user), user %></h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <div class="btn-group justify-content-between">
              <%= link_to "View profile", user, class: "btn btn-outline-info border-0" %>
              <% if logged_in? %>
                <% if user == current_user %>
                  <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-success border-0" %>
                <% end %>

                <% if current_user.admin? %>
                  <%= button_to "Delete user", user_path(user),
                  method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete },
                  class: "btn btn-outline-danger border-0" %>
                <% end %>
              <% end %>
            </div>
          </div>

          <div class="card-footer text-body-secondary">
            <small>
              Joined <%= time_ago_in_words(user.created_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="apple_pagination mx-auto mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %></h1>

<%= gravatar_for @user%>

<div class="text-center mt-4">
  <%= link_to "Back to list", users_path, class: "btn btn-secondary" %>
  <% if logged_in? && @user == current_user %>
    <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-success" %>
  <% end %>
</div>

<h2 class="text-center mt-4">Articles</h2>

<div class="apple_pagination mx-auto">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination mx-auto mb-4">
  <%= will_paginate @articles, :container => false %>
</div>